# Generated by Django 4.2.6 on 2023-12-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('animeID', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(null=True)),
                ('generos', models.TextField(null=True)),
                ('formato_emision', models.TextField(null=True)),
                ('num_episodios', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('num_episodios',),
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.PositiveIntegerField(null=True)),
                ('puntuacion', models.PositiveSmallIntegerField()),
                ('animeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
        ),
    ]
